name: Deploy on EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docker_build:
    name: Build and push docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/wkk-offcial/lavalink_server:latest

  deploy:
    name: Deploy to EC2
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Image on EC2
      uses: appleboy/ssh-action@v0.1.8
      env:
        LAVALINK_IMAGE: "ghcr.io/wkk-offcial/lavalink_server:latest"
        LAVALINK_CONTAINER_NAME: "lavalink_server"
        LAVALINK_ABS_PATH_ROOT: "/home/ec2-user/Lavalink_server/"
        LAVALINK_REL_YML_PATH: "conf/application.yml"
      with:
        host: ${{secrets.BOI_HOSTNAME}}
        username: ec2-user
        key: ${{secrets.BOI_PRIVATE_KEY}}
        envs: LAVALINK_IMAGE, LAVALINK_CONTAINER_NAME, LAVALINK_ABS_PATH_ROOT, LAVALINK_REL_YML_PATH
        script_stop: true
        script: |
          if [[ -z "$(docker network ls | grep wkk-network)" ]]; then
            docker network create wkk-network
          fi
          if [[ -z "$(docker volume ls | grep sounds)" ]]; then
            docker volume create sounds
          fi
          docker pull $LAVALINK_IMAGE
          docker stop $LAVALINK_CONTAINER_NAME && docker rm -fv $LAVALINK_CONTAINER_NAME || true
          docker run -d \
                     -v "${LAVALINK_ABS_PATH_ROOT}${LAVALINK_REL_YML_PATH}:/home/Lavalink/application.yml" \
                     -v "sounds:/home/Lavalink/sounds/" \
                     -p 36969:2333 \
                     --restart unless-stopped \
                     --network="wkk-network" \
                     --name $LAVALINK_CONTAINER_NAME $LAVALINK_IMAGE
          docker image prune <<< y
